### PR TITLE
Add systemd init for jessie

### PR DESCRIPTION
**Pull request by jdupl**
Tested on fresh debian jessie

### CODE REVIEW

**Comment by jdupl** [comment]
closes #79

**Comment by jdupl** [comment]
@Kerwood updated readme

**Comment by Kerwood** [comment]
Great job.. Very nicely.. 
But why use tmux ? .. In my experience tmux has a tendency to hawg memory and perform badly under pressure. 

If you dont mind I would really like you to change the function to use screen instead. I would really apreciate that. :)

**Comment by jdupl** [comment]
Tmux has more to offer and has better default config (having a good status bar in screen is a bit painfull). Personnally, I switched to tmux and had no problems with it.

But the main fact is that tmux is actively developed.

**Comment by Kerwood** [comment]
My only concern is that users (that are not good at Linux) gets confused. 
But okay.. Lets see how this goes and we can always change it if I get to many confusing questions it.

Apreciate your work.

**Comment by jdupl** [comment]
no problems I understand

**Pull request merged**
