### PR TITLE
Create Rtorrent-Auto-Install-3.0.2-Raspbian-Wheezy

### PR DESCRIPTION
**Pull request by miracle091**
Changed some words and re-formatted the entire file (spaces, etc)
Removed "apache2-utils" from APT-DEPENDENCIES function, cause is already installed in APACHE-UTILS function
Added raspberrypi logo, thanks to piksel https://gist.github.com/piksel/3023588
Added recommended plugins
Added a exit choise

Working with Raspbian Wheezy

### CODE REVIEW

**Comment by jdupl** [comment]
Is there a way to make this compatible with the main script ? 
Maintaining this means doubling the work.

**Comment by miracle091** [comment]
Is the same script, but this is for make some people (like me happy), for now.
I would use Lighttod in the next version instead of Apache2, cause require too much resource to work well for the raspberry.

P.S Work on model B and B+ (tested both), maybe B Gen2 but not have tried it. Work on A and A+ too but i have not tested it.

**Comment by miracle091** [comment]
And maybe change some env variables to compile more fast...with the base variables take like 40-50 minutes.

**Comment by Kerwood** [comment]
That is awesome!... Good work :+1:

**Comment by miracle091** [comment]
The init.d script, after 3 days from installation, don't work anymore. I am trying to understand what is wrong with that.
For now use the manual command to start/stop rtorrent.

Sorry for the inconvenience.

**Pull request merged**
