### PR TITLE
Fixed the GeoIP plugin dependencies

### PR DESCRIPTION
**Pull request by frantzz**
Fixed the GeoIP plugin dependencies and removed unused files.

### CODE REVIEW

**Comment by Kerwood** [comment]
Not really sure what happened here :D

**Comment by Kerwood** [comment]
Why is the "No need to disable 000-default anymore" request here ?

**Comment by frantzz** [comment]
Haha yeah me too. I just wanted to pull my commit "Fixed the GeoIP plugin dependencies" and "	Removed unused files" but It also sent an old one commit (No need to disable 000-default anymore) :S

**Comment by Kerwood** [comment]
Not really sure what to do here.. :)



*Med venlig hilsen*
*Patrick Kerwood*

http://LinuxBloggen.dk

2015-03-16 13:05 GMT+01:00 Frantz <notifications@github.com>:

**Comment by frantzz** [comment]
Hum.. I'll do another commit then. Sorry for that.

**Pull request closed without merging**
