### PR TITLE
Update Plugins-installer-script-2.1

### PR DESCRIPTION
**Pull request by miracle091**
Updated with the functions taken from the others scripts

### CODE REVIEW

**Comment by Kerwood** [comment]
Looks good.. Have you tested it ?

**Comment by miracle091** [comment]
All optiona except for the all plugins choise

**Comment by Kerwood** [comment]
Maybe you should cancel the pull request, create a new file and call it "Plugins-installer-script-3.0" and make pull request again.

**Comment by Kerwood** [comment]
Just rename file and add it.

**Pull request closed without merging**
